# Generated by Django 2.0.10 on 2020-04-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20200428_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='used_inivitations',
            new_name='used_invitations',
        ),
    ]
