# Generated by Django 2.0.10 on 2020-05-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_invitation'),
        ('users', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rides',
            new_name='Ride',
        ),
    ]
